### PR TITLE
release: Version 4.2.0

### PR DESCRIPTION
**Pull request by robwalkerco**
Bumping version to 4.2.0 and updating changelog

### CODE REVIEW

**Review by cortinico — APPROVED** [review]

**Comment by cortinico** [comment]
@philIip do you need me to release this to NPM?

**Comment by yungsters** [comment]
@cortinico, in the past we published new releases of this package alongside new releases of `react-native`.

I haven't checked, but were these changes already part of 0.72?

**Comment by yungsters** [comment]
Oh wait, looks like we have a precedent for incrementally publishing new minors when adding props (see 4.1.0).

Unless we feel strongly otherwise, it seems fine to publish 4.2.0 with this.

**Comment by cortinico** [comment]
> in the past we published new releases of this package alongside new releases of `react-native`.

@yungsters I don't recall us publishing this for every version of React Native. It was more on a case by case basis. I'll merge and release this one then 👍

**Comment by cortinico** [comment]
```
+ deprecated-react-native-prop-types@4.2.0
```

should be available now 👍

**Pull request merged**
